FROM openjdk:17

WORKDIR /usr/src/microservice/

COPY /home/runner/work/microservice-instant-message-project/microservice-instant-message-project/microservice-instant-message/target/microservice-instant-message.jar /usr/src/microservice/

CMD ["java","-jar","microservice-instant-message.jar"]
