CREATE TABLE "user" (
    "INSTANT_MESSAGING_SOFTWARE" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID" VARCHAR(255) NOT NULL,
    "USER_NAME" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
);

CREATE TABLE "group" (
    "GROUP_ID" VARCHAR(255) NOT NULL,
    "GROUP_NAME" VARCHAR(255) NOT NULL,
    "GROUP_WEBHOOK" VARCHAR(255) NULL,
    "AUTHORIZATION_KEY" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID")
);

CREATE TABLE "member" (
    "GROUP_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY"),
    FOREIGN KEY ("GROUP_ID_FOREIGN_KEY") REFERENCES "group"("GROUP_ID"),
    FOREIGN KEY ("INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY") REFERENCES "user"("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
);

CREATE TABLE "manager" (
    "GROUP_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY"),
    FOREIGN KEY ("GROUP_ID_FOREIGN_KEY") REFERENCES "group"("GROUP_ID"),
    FOREIGN KEY ("INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY") REFERENCES "user"("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
);