CREATE TABLE "USER" (
    "INSTANT_MESSAGING_SOFTWARE" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID" VARCHAR(255) NOT NULL,
    "USER_NAME" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
); 

CREATE TABLE "GROUP" (
    "GROUP_ID" VARCHAR(255) NOT NULL,
    "GROUP_NAME" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID")
);

CREATE TABLE "MEMBER" (
    "GROUP_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY"),
    FOREIGN KEY ("GROUP_ID_FOREIGN_KEY") REFERENCES "GROUP"("GROUP_ID"),
    FOREIGN KEY ("INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY") REFERENCES "USER"("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
);

CREATE TABLE "MANAGE" (
    "GROUP_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    "INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("GROUP_ID_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY"),
    FOREIGN KEY ("GROUP_ID_FOREIGN_KEY") REFERENCES "GROUP"("GROUP_ID"),
    FOREIGN KEY ("INSTANT_MESSAGING_SOFTWARE_FOREIGN_KEY","INSTANT_MESSAGING_SOFTWARE_USER_ID_FOREIGN_KEY") REFERENCES "USER"("INSTANT_MESSAGING_SOFTWARE","INSTANT_MESSAGING_SOFTWARE_USER_ID")
);