server:
  port: 8080
info: 
  app: 
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
management:
  security:
    enabled: false
line.bot:
  channel-token: '${LINE_BOT_TOKEN}'
  channel-secret: '${LINE_BOT_SECRET}'
  handler.path: ${LINE_WEBHOOK}
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    url: jdbc:h2:file:./src/main/resources/db/h2file/h2
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2console/
  liquibase.change-log: db/changelog/db.changelog-master-h2.sql
logging:                                
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE


##for debug
##logging:
  ##level:
    ##org.springframework: DEBUG
