#/home/runner/work/microservice-instant-message-project/microservice-instant-message-project/microservice-instant-message/pom.xml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: mvn -B -f /home/runner/work/microservice-instant-message-project/microservice-instant-message-project/microservice-instant-message/pom.xml clean package

    - name: Test
      run: mvn -B -f /home/runner/work/microservice-instant-message-project/microservice-instant-message-project/microservice-instant-message/pom.xml test

    - name: Dockerize
      run: docker build -t -f /home/runner/work/microservice-instant-message-project/microservice-instant-message-project/Dockerfile-microservice-instant-message microservice-instant-message:latest .

    - name: Publish Docker image
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push microservice-instant-message:latest

