#/home/runner/work/microservice-instant-message-project/microservice-instant-message-project/microservice-instant-message/pom.xml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn -B -f microservice-instant-message/pom.xml clean install

    - name: Test
      run: mvn -B -f microservice-instant-message/pom.xml test
      
    - name: Debug
      run: |
        pwd
        ls -la
        ls -la microservice-instant-message
        ls -la microservice-instant-message/target
      
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
      run: |
        docker build -t microservice-instant-message:latest -f Dockerfile-microservice-instant-message .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag microservice-instant-message tairitsu86/microservice-instant-message
        docker push tairitsu86/microservice-instant-message:latest
        
        
        
